name: flutter_boarding
description: A Simply create introduction board in Flutter, create [Boading] based on parent key.
version: 0.1.0-dev.3
homepage: https://github.com/farhanfadila1717/flutter_board
maintener: Farhan Fadila (@farhanfadila1717)

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

